#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"
sudo cp cf.* /Library/Keyboard\ Layouts
sudo touch /Library/Keyboard\ Layouts
echo "Installation du clavier Canadien Français terminée."
open /System/Library/PreferencePanes/Keyboard.prefPane
